version: '3'

services:
  server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - servervol:/serverdata

volumes:
  servervol:

networks: 
  default: 
    external: 
      name: my-network 
